version: '3.4'
services:
  hpotter:
    build: .
    ports:
      - "23:23"
      - "80:8080"
    depends_on: 
      - mariadb
    networks:
      - backend
    environment:
      HPOTTER_DB: mysql
      HPOTTER_DB_USER: ${HPOTTER_DB_USER}
      HPOTTER_DB_PASSWORD: ${HPOTTER_DB_PASSWORD}
      HPOTTER_DB_HOST: mariadb
      HPOTTER_DB_PORT: 3306
      HPOTTER_DB_DB: ${HPOTTER_DB_DB}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  jsonserver:
    build: .
    ports:
      - "8000:8000"
    depends_on: 
      - mariadb
    networks:
      - backend
    environment:
      HPOTTER_DB: mysql
      HPOTTER_DB_USER: ${HPOTTER_DB_USER}
      HPOTTER_DB_PASSWORD: ${HPOTTER_DB_PASSWORD}
      HPOTTER_DB_HOST: mariadb
      HPOTTER_DB_PORT: 3306
      HPOTTER_DB_DB: ${HPOTTER_DB_DB}
    restart: always
    command: 'hpotter.jsonserver'
    
  mariadb:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: ${HPOTTER_DB_PASSWORD}
      MYSQL_DATABASE: ${HPOTTER_DB_DB}
      MYSQL_USER: ${HPOTTER_DB_USER}
      MYSQL_PASSWORD: ${HPOTTER_DB_PASSWORD}
    networks:
      - backend
    restart: always
    volumes:
     - db_data:/var/lib/mysql

networks:
  backend:
    driver: bridge

volumes:
  db_data: {}
